# Generated by Django 5.0.7 on 2024-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arroba', models.CharField(max_length=25)),
                ('range', models.CharField(max_length=10)),
                ('seguidores', models.BigIntegerField()),
                ('score_medio', models.FloatField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
