# Generated by Django 5.0.7 on 2024-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_influ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='score_medio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='seguidores',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
