# Generated by Django 5.0.7 on 2024-07-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_influ', '0002_alter_influencer_foto_alter_influencer_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='arroba',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
